### ISSUE TITLE
Question: Is it good that existence Kconfig and <variant>/config.txt are optional?

### ISSUE THREAD

**Issue by basejumpa** [avengineers/spl-core#14]
Question: Is it good that existence Kconfig and <variant>/config.txt are optional?

Related code:

* https://github.com/avengineers/SPL/blob/57c8799d7023a37b89099ee6b84c814091ae0e2d/cmake/kconfig.cmake#L32
* https://github.com/avengineers/SPL/blob/57c8799d7023a37b89099ee6b84c814091ae0e2d/cmake/kconfig.cmake#L14

If we decide that they need to be mandatory, then above lines need to be adapted from `STATUS` to `FATAL_ERROR`. So code changes are very small.

**Comment by xxthunder** [comment]
Good question. Currently we have no issues with that.
